# FileName: Install-Application.ps1
# Powershell/Choco Script for Building Dev Machine
#
# Generated by: Mario Fialho
#
# Generated on: 7/19/2018
#

#Progress parameter
$Progress = @{
    Activity = 'Installing packages:'
    CurrentOperation = "Loading"
    Status = 'Installing'
    PercentComplete = 0
}
  
Write-Progress @Progress
$i = 0

##Check if Choco is installed
#If so, install packages
#If not install Choco and then install packages
If(Test-Path -Path "$env:ProgramData\Chocolatey") {
    Install-ChocoPackages
}
Else {
    Install-Choco
    Install-ChocoPackages
}

##Choco Installer
##Install choco .exe and add choco to PATH
function Install-Choco {
    Powershell -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
    SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
}


function Install-ChocoPackages {
    Write-Host "Starting the Installation of the Chocolatey Applications Packages" -ForegroundColor Yellow
    $Packages = 'googlechrome', 'git', 'notepadplusplus', 'sql-server-management-studio' , 'firefox', 'visualstudiocode' , 
            'notepadplusplus' , 'ondrive' , 'sublimetext3' , 'vlc' , 'atom' , 'node.js' , '7zip.install' , 'dropbox' , 
            'slack' , 'microsoft-teams' , 'office365proplus'
    ForEach ($PackageName in $Packages) 
    {
        $i++
        [int]$percentage = ($i / $Packages.Count)*100
        $Name = $null
        $Name = $file.name
        $progress.CurrentOperation = "$name"
        $progress.Status = 'Installing Package: '
        $progress.PercentComplete = $percentage
  
        Write-Progress @Progress
     
        Start-Sleep -Milliseconds 600                                
        Try 
        {
            choco install $PackageName -y
            #Write-Host "Install Percentage:" $percentage
        }
        Catch 
        {
            Write-Warning $_.Exception.Message
            Continue        
        }       
    }
}

